Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('pi = ',np.pi)
print('e = ',np.e)
print('euler gamma = ',np.euler_gamma)

print('infinity = ',np.Inf)
print('infinity = ',np.Infinity)
print('infinity = ',np.inf)
print('infinity = ',np.infty)
print('positive infinity = ',np.PINF)
print('negative infinity = ',np.NINF)

print('positive zero = ',np.PZERO)
print('negative zero = ',np.NZERO)

print('nan = ',np.nan)
print('nan = ',np.NAN)
print('nan = ',np.NaN)

print('None/newaxis = ',np.newaxis)
------------------

----- stdout -----
pi =  3.141592653589793
e =  2.718281828459045
euler gamma =  0.5772156649015329
------------------

[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[12][39m[32m, line 5[39m
[32m      2[39m [38;5;28mprint[39m([33m'[39m[33me = [39m[33m'[39m,np.e)
[32m      3[39m [38;5;28mprint[39m([33m'[39m[33meuler gamma = [39m[33m'[39m,np.euler_gamma)
[32m----> [39m[32m5[39m [38;5;28mprint[39m([33m'[39m[33minfinity = [39m[33m'[39m,[43mnp[49m[43m.[49m[43mInf[49m)
[32m      6[39m [38;5;28mprint[39m([33m'[39m[33minfinity = [39m[33m'[39m,np.Infinity)
[32m      7[39m [38;5;28mprint[39m([33m'[39m[33minfinity = [39m[33m'[39m,np.inf)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/numpy/__init__.py:400[39m, in [36m__getattr__[39m[34m(attr)[39m
[32m    397[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr], name=[38;5;28;01mNone[39;00m)
[32m    399[39m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __expired_attributes__:
[32m--> [39m[32m400[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[32m    401[39m         [33mf[39m[33m"[39m[33m`np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[33m` was removed in the NumPy 2.0 release. [39m[33m"[39m
[32m    402[39m         [33mf[39m[33m"[39m[38;5;132;01m{[39;00m__expired_attributes__[attr][38;5;132;01m}[39;00m[33m"[39m,
[32m    403[39m         name=[38;5;28;01mNone[39;00m
[32m    404[39m     )
[32m    406[39m [38;5;28;01mif[39;00m attr == [33m"[39m[33mchararray[39m[33m"[39m:
[32m    407[39m     warnings.warn(
[32m    408[39m         [33m"[39m[33m`np.chararray` is deprecated and will be removed from [39m[33m"[39m
[32m    409[39m         [33m"[39m[33mthe main namespace in the future. Use an array with a string [39m[33m"[39m
[32m    410[39m         [33m"[39m[33mor bytes dtype instead.[39m[33m"[39m, [38;5;167;01mDeprecationWarning[39;00m, stacklevel=[32m2[39m)

[31mAttributeError[39m: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

